import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import {getAllPosts, Post} from '../lib/post'
import {getAllProjects, Project} from '../lib/project'
import PostItem from '../components/PostItem'
type HomeProps = {
  posts: Post[],
  projects: Project[]
}
export default function Home({posts, projects} : HomeProps) {
  return (
    <div className="bg-gray-100 h-full min-h-screen	">

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pt-20">
      {posts.map((post, i) => (
        <PostItem post={post} key={i} />
      ))}
      {projects.map((project, i) => (
        <div key={i}>
          <h2><Link href={`/project/${project.slug}`}>{project.meta.title}</Link></h2>
        </div>
      ))}
      </div>
    </div>
  )
}


export async function getStaticProps() {
  return {
    props: {
      posts: await getAllPosts(),
      projects: await getAllProjects()
    }
  }
}